# Generated by Django 6.1.1 on 2026-10-02 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=250)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('organizador', models.ForeignKey(limit_choices_to={'rol': 'ORGANIZADOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to=settings.AUTH_USER_MODEL)),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='api.recinto')),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='api.evento')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('evento', 'nombre'), name='sector_unico_por_evento'), models.CheckConstraint(condition=models.Q(('precio__gt', 0)), name='sector_precio_positivo')],
            },
        ),
    ]
