# Generated by Django 6.1.1 on 2026-10-02 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recinto_evento_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.compra')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='api.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('valida', models.BooleanField(default=True)),
                ('utilizada', models.BooleanField(default=False)),
                ('emitida', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='api.detallecompra')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.carro')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_carro', to='api.sector')),
            ],
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='total_compra_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='detallecompra',
            constraint=models.UniqueConstraint(fields=('compra', 'sector'), name='sector_unico_en_compra'),
        ),
        migrations.AddConstraint(
            model_name='detallecompra',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 1)), name='cantidad_compra_positiva'),
        ),
        migrations.AddConstraint(
            model_name='detallecompra',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gt', 0)), name='precio_detalle_positivo'),
        ),
        migrations.AddConstraint(
            model_name='itemcarro',
            constraint=models.UniqueConstraint(fields=('carro', 'sector'), name='sector_unico_en_carro'),
        ),
        migrations.AddConstraint(
            model_name='itemcarro',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 1)), name='cantidad_carro_positiva'),
        ),
    ]
