# Generated by Django 6.1.1 on 2026-10-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_carro_compra_detallecompra_entrada_itemcarro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='es_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
