# Generated by Django 6.1.1 on 2026-10-02 23:00

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_evento_es_demo_evento_imagen_url'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden', models.CharField(max_length=26, unique=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AUTORIZADO', 'Autorizado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado'), ('REEMBOLSADO', 'Reembolsado'), ('REVISION', 'Requiere conciliación')], default='PENDIENTE', max_length=20)),
                ('ambiente', models.CharField(default='integration', max_length=12)),
                ('autorizacion', models.CharField(blank=True, max_length=20)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('CONFIRMADO', 'Confirmado'), ('REVISION', 'Revisión')], max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('POP', 'Pop'), ('KPOP', 'K-pop'), ('ROCK', 'Rock'), ('URBANO', 'Urbano'), ('ELECTRONICA', 'Electrónica'), ('INDIE', 'Indie / Alternativo'), ('JAZZ', 'Jazz / Blues'), ('CLASICA', 'Música clásica'), ('TEATRO', 'Teatro / Comedia'), ('FAMILIAR', 'Familiares'), ('OTROS', 'Otros eventos')], default='OTROS', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='documento_extranjero',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='extranjero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='usuario_email_unico'),
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compra',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='api.pago'),
        ),
        migrations.AddField(
            model_name='reembolso',
            name='compra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reembolso', to='api.compra'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('total__gt', 0)), name='pago_total_positivo'),
        ),
    ]
