# Generated by Django 6.1.1 on 2026-10-02 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pago_reembolso_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='asientos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='itemcarro',
            name='asientos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(max_length=4)),
                ('numero', models.PositiveIntegerField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='api.sector')),
            ],
            options={
                'ordering': ['fila', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='entrada',
            name='asiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='api.asiento'),
        ),
        migrations.AddConstraint(
            model_name='entrada',
            constraint=models.UniqueConstraint(condition=models.Q(('asiento__isnull', False), ('valida', True)), fields=('asiento',), name='entrada_valida_unica_asiento'),
        ),
        migrations.AddConstraint(
            model_name='asiento',
            constraint=models.UniqueConstraint(fields=('sector', 'fila', 'numero'), name='asiento_unico_sector'),
        ),
    ]
